const PRODUCT_SEED = [
  {
    product_code: "track_chaos",
    product_type: "track",
    slug: "chaos",
    title: "CHAOS",
    lane: "red",
    base_price_pence: 269,
    sale_price_pence: null,
    sale_enabled: false,
    sale_group: null,
    guest_visible: true,
    premium_visible: true,
    purchase_grants_premium_mode: true,
    website_streamable_after_purchase: true,
    direct_download_included: true,
    artwork_pack_included: true,
    lyric_sheet_included: false,
    collector_note_included: false,
    vault_only: false,
    active: true
  },
  {
    product_code: "track_bonfire",
    product_type: "track",
    slug: "bonfire",
    title: "BONFIRE",
    lane: "blue",
    base_price_pence: 269,
    sale_price_pence: null,
    sale_enabled: false,
    sale_group: null,
    guest_visible: true,
    premium_visible: true,
    purchase_grants_premium_mode: true,
    website_streamable_after_purchase: true,
    direct_download_included: true,
    artwork_pack_included: true,
    lyric_sheet_included: false,
    collector_note_included: false,
    vault_only: false,
    active: true
  },
  {
    product_code: "track_star",
    product_type: "track",
    slug: "star",
    title: "STAR",
    lane: "yellow",
    base_price_pence: 269,
    sale_price_pence: null,
    sale_enabled: false,
    sale_group: null,
    guest_visible: true,
    premium_visible: true,
    purchase_grants_premium_mode: true,
    website_streamable_after_purchase: true,
    direct_download_included: true,
    artwork_pack_included: true,
    lyric_sheet_included: false,
    collector_note_included: false,
    vault_only: false,
    active: true
  },
  {
    product_code: "track_mary",
    product_type: "track",
    slug: "mary",
    title: "MARY",
    lane: "green",
    base_price_pence: 269,
    sale_price_pence: 178,
    sale_enabled: true,
    sale_group: "rotating_promo",
    guest_visible: true,
    premium_visible: true,
    purchase_grants_premium_mode: true,
    website_streamable_after_purchase: true,
    direct_download_included: true,
    artwork_pack_included: true,
    lyric_sheet_included: false,
    collector_note_included: false,
    vault_only: false,
    active: true
  },
  {
    product_code: "track_edge",
    product_type: "track",
    slug: "edge",
    title: "EDGE",
    lane: "red",
    base_price_pence: 269,
    sale_price_pence: 178,
    sale_enabled: true,
    sale_group: "rotating_promo",
    guest_visible: true,
    premium_visible: true,
    purchase_grants_premium_mode: true,
    website_streamable_after_purchase: true,
    direct_download_included: true,
    artwork_pack_included: true,
    lyric_sheet_included: false,
    collector_note_included: false,
    vault_only: false,
    active: true
  },
  {
    product_code: "track_jimmy",
    product_type: "track",
    slug: "jimmy",
    title: "JIMMY",
    lane: "blue",
    base_price_pence: 269,
    sale_price_pence: 178,
    sale_enabled: true,
    sale_group: "rotating_promo",
    guest_visible: true,
    premium_visible: true,
    purchase_grants_premium_mode: true,
    website_streamable_after_purchase: true,
    direct_download_included: true,
    artwork_pack_included: true,
    lyric_sheet_included: false,
    collector_note_included: false,
    vault_only: false,
    active: true
  },
  {
    product_code: "vault_swim_edition_1",
    product_type: "vault_drop",
    slug: "swim",
    title: "SWIM",
    lane: "red",
    base_price_pence: 499,
    sale_price_pence: null,
    sale_enabled: false,
    sale_group: null,
    guest_visible: true,
    premium_visible: true,
    purchase_grants_premium_mode: true,
    website_streamable_after_purchase: false,
    direct_download_included: false,
    artwork_pack_included: false,
    lyric_sheet_included: false,
    collector_note_included: true,
    vault_only: true,
    active: true
  },
  {
    product_code: "bundle_01",
    product_type: "bundle",
    slug: "bundle-01",
    title: "Bundle 01",
    lane: "mixed",
    base_price_pence: 500,
    sale_price_pence: null,
    sale_enabled: false,
    sale_group: null,
    guest_visible: true,
    premium_visible: true,
    purchase_grants_premium_mode: true,
    website_streamable_after_purchase: false,
    direct_download_included: true,
    artwork_pack_included: true,
    lyric_sheet_included: false,
    collector_note_included: true,
    vault_only: true,
    active: true
  }
];

const BUNDLE_ITEM_SEED = [
  {
    bundle_product_code: "bundle_01",
    item_product_code: "track_chaos",
    position: 1
  },
  {
    bundle_product_code: "bundle_01",
    item_product_code: "track_star",
    position: 2
  },
  {
    bundle_product_code: "bundle_01",
    item_product_code: "track_bonfire",
    position: 3
  }
];

const PROMO_RULE_SEED = {
  promo_group: "rotating_promo",
  cadence_days: 14,
  selection_mode: "random_from_pool",
  pool_product_codes: [
    "track_jimmy",
    "track_edge",
    "track_mary"
  ],
  active_count: 3,
  strike_price_pence: 269,
  promo_price_pence: 178
};
